---
# Changes here will be overwritten by Copier
_commit: v2.2.0
_src_path: gh:remerge/template
project_id: terraform-modules
project_license: apache-2.0
project_name: Terraform Modules
project_owner: core
project_type: terraform-module
run_workflows_for_all_branches: false
use_python: false
