---
# Changes here will be overwritten by Copier
_commit: v1.13.2-12-g93b3f77
_src_path: gh:remerge/template
deploy_branch: production
google_cloud_gke_master_subnet: None
google_cloud_project: terraform-modules-[random_id]
google_cloud_region: europe-west4
google_cloud_zone: europe-west4-a
project_description: Collection of reusable Terraform modules
project_id: terraform-modules
project_license: apache-2.0
project_name: Terraform Modules
project_owner: sre
project_type: terraform-module
use_ansible: false
use_docker: false
use_golang: false
use_google_cloud_compute: false
use_google_cloud_gke: false
use_python: false
use_terraform: false
use_terraform_google: false
