---
name: pre-commit

on:
  pull_request:
  push:
    branches: [main, master]

permissions:
  actions: none
  checks: none
  contents: read
  deployments: none
  discussions: none
  id-token: none
  issues: none
  packages: none
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  # terraform downloads from the private registry which requires authentication.
  TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_APP_TERRAFORM_IO }}

jobs:
  pre-commit:
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - name: Checkout repository
        # https://github.com/actions/checkout/releases
        uses: actions/checkout@v7.0.0

      - name: Setup SSH agent
        # https://github.com/webfactory/ssh-agent/releases
        uses: webfactory/ssh-agent@v0.10.0
        with:
          ssh-private-key: "${{ secrets.DEPLOY_USER_SSH_KEY }}"

      - name: Setup Git
        run: |
          curl -f -sL --retry 5 --retry-delay 1 https://api.github.com/meta | jq -r '"github.com "+.ssh_keys[]' >> ~/.ssh/known_hosts
          git config --global url."git@github.com:".insteadOf "https://github.com/"
          git config --global advice.detachedHead false

      - name: Setup Python
        uses: actions/setup-python@v6.3.0
        with:
          python-version: "3.14"

      - name: Setup Terraform
        # https://github.com/hashicorp/setup-terraform/releases
        uses: hashicorp/setup-terraform@v4.0.1

      - name: Cache Terraform providers
        # https://github.com/actions/cache/releases
        uses: actions/cache@v6.1.0
        with:
          path: ~/.cache/terraform/plugins
          key: "${{ runner.os }}-tf-plugins-${{ hashFiles('**/.terraform.lock.hcl') }}"

      # https://github.com/actions/setup-node/issues/531
      - run: corepack enable

      - name: Setup NodeJS
        # https://github.com/actions/setup-node/releases
        uses: actions/setup-node@v7.0.0
        with:
          node-version: "24"

      - name: Load envrc
        # https://github.com/HatsuneMiku3939/direnv-action/releases
        uses: HatsuneMiku3939/direnv-action@v1.4.1

      - name: Install project dependencies
        run: make install

      - name: Run pre-commit checks
        # https://github.com/pre-commit/action/releases
        uses: pre-commit/action@v3.0.1
